# Site settings
title: Madhusruti Das Portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio! I'm Madhusruti Das, a passionate software developer with interests in cricket, music, and more. Explore my projects, learn about my background in Computer Science and Engineering, and get in touch!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your_twitter_username
github_username: your_github_username

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
