name: CI/CD Pipeline with Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd Portfolio
        npm install

    - name: Build
      run: |
        cd Portfolio
        npm run build

    - name: Run security check
      uses: snyk/actions/node@master
      with:
        args: test
      env:
        SNYK_TOKEN: ${{ secrets.MAD }}
