name: Deploy to GitHub Pages with Security Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Run security check
      uses: snyk/actions/node@master
      with:
        args: test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Deploy to GitHub Pages
      id: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MAD}}
        publish_dir: ./_site

    - name: Show URL
      run: echo "Website deployed at https://motorshuti.github.io/Portfolio/"

    - name: Set output URL
      run: echo "::set-output name=url::https://motorshuti.github.io/Portfolio/"

    - name: Output URL
      run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
