name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./_site

      - name: Show URL
        run: echo "Website deployed at https://motorshuti.github.io/Portfolio/"

      - name: Set output URL
        run: echo "::set-output name=url::https://motorshuti.github.io/Portfolio/"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Output URL
        run: echo "Deployed to ${{ needs.deploy.outputs.url }}"

  workflows:
    deploy:
      jobs:
        - deploy
        - notify:
            needs: deploy
            runs-on: ubuntu-latest
            if: always()
